# Étape 1: Build de l'application Vue.js
FROM node:20.14.0 AS build-stage
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2: Configuration de Nginx pour servir l'application
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]