name: Elixir Phoenix CI

on:
  push:
    branches:
      - '*'
      # all except the following
      - '!master'
      - '!main'  
  pull_request:
    branches:
      - '*'
      # all except the following
      - '!master'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest


    services:
      postgres: 
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: timeuser
          POSTGRES_PASSWORD: timepassword
          POSTGRES_DB: timemanagement
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.17.3'
        otp-version: '27'

    - name: Install dependencies
      run: mix deps.get
    
    - name: Set up database
      run: |
        mix ecto.create
        mix ecto.migrate
        mix ecto.generate 

    - name: Run tests
      run: mix test

